### ISSUE TITLE
Water appears as Green textures

### ISSUE THREAD

**Issue by Mrblubb** [ThirteenAG/MafiaWaterShaderMod#4]
When using this mod with the retail disk version 1.0 and widescreen fix, all the water just looks like green textures.
![vlcsnap-2024-03-22-18h38m10s982](https://github.com/ThirteenAG/MafiaWaterShaderMod/assets/88938655/dd91c214-5ba0-4ae6-9367-aa00f891c1a4)
![vlcsnap-2024-03-22-18h38m18s580](https://github.com/ThirteenAG/MafiaWaterShaderMod/assets/88938655/f9a2b1a5-4a99-4280-a48c-0c4792c27dee)
![vlcsnap-2024-03-22-18h38m43s225](https://github.com/ThirteenAG/MafiaWaterShaderMod/assets/88938655/82f26458-a809-4606-ab99-6cf6ace09a3f)

**Comment by Patrxgt** [comment]
This bug is exclusive to the 1.0 version of the game. It looks like this mod requires version 1.2 to work properly.

**Comment by Mrblubb** [comment]
Oh I see. Thanks for the help. If so I think it will work on updated GOG version as well. I was hoping since the retail 1.0 version has eye animations & car scratch decals it should be working on that too.

**Comment by Patrxgt** [comment]
You can still get water with reflections on 1.0 if you use the original mod by Mr F, since it has a support for all of the version of Mafia.
